name: Discord Notifications

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Discord
        uses: tsickert/discord-webhook@v5
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GitHub Bot"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          embeds: |
            [
              {
                "title": "🔔 Novo evento no GitHub",
                "description": "Um evento foi registrado no repositório **${{ github.repository }}**",
                "color": 5814783,
                "fields": [
                  {
                    "name": "Evento",
                    "value": "${{ github.event_name }}",
                    "inline": true
                  },
                  {
                    "name": "Autor",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Repositório",
                    "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                  }
                ],
                "footer": {
                  "text": "GitHub → Discord Notifier"
                },
                "timestamp": "${{ github.event.pull_request.updated_at || github.event.issue.updated_at }}"
              }
            ]
